### ISSUE TITLE
epub.js:12759 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getAttribute')

### ISSUE THREAD

**Issue by wizardforcel** [futurepress/epubjs-reader#63]
console error:

```
epub.js:12759 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getAttribute')
    at Navigation.ncxItem (epub.js:12759:22)
    at Navigation.parseNcx (epub.js:12734:17)
    at Navigation.parse (epub.js:12495:21)
    at new Navigation (epub.js:12467:9)
    at epub.js:10416:25
ncxItem @ epub.js:12759
parseNcx @ epub.js:12734
parse @ epub.js:12495
Navigation @ epub.js:12467
（匿名） @ epub.js:10416
Promise.then（异步）
unpack @ epub.js:10349
（匿名） @ epub.js:10185
Promise.then（异步）
openPackaging @ epub.js:10183
（匿名） @ epub.js:10148
Promise.then（异步）
openEpub @ epub.js:10147
Promise.then（异步）
open @ epub.js:10117
Book @ epub.js:10084
ePub @ epub.js:9804
EPUBJS.Reader @ reader.js:67
root.ePubReader @ reader.js:10
document.onreadystatechange @ （索引）:24
epub.js:7295 Uncaught TypeError: Cannot read properties of undefined (reading 'pageFromCfi')
    at Rendition.located (epub.js:7295:39)
    at Rendition.reportedLocationAfterRAF (epub.js:7188:26)
```

sample epub (need to unzip):

[file.epub.zip](https://github.com/futurepress/epubjs-reader/files/8779260/file.epub.zip)

**Comment by gordon-matt** [comment]
I am seeing a similar issue with a particular epub:

```
Uncaught (in promise) TypeError: can't access property "getAttribute", Object(...)(...) is null
    ncxItem https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    parseNcx https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    parse https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    S https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    loadNavigation https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    promise callback*loadNavigation https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    unpack https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    openPackaging https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    promise callback*openPackaging https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    openEpub https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    promise callback*openEpub https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    promise callback*open https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    H https://localhost:44339/lib/epubjs/dist/epub.min.js:1
    l https://localhost:44339/lib/epubjs/dist/epub.min.js:1
epub.min.js:1:166895
```

Version: epub.js 0.3.93

Stack trace matches this issue exactly: Navigation.ncxItem → parseNcx → parse during loadNavigation / unpack, so book.ready rejects and the book never opens.

Root cause (invalid NCX, not a timing/DOM issue)

In our case the EPUB is EPUB 2 with a calibre/Sigil-style stub toc.ncx: a single navPoint with an empty `<navLabel>` and no `<content>` child. NCX requires every navPoint to have `<content src="…"/>`.

Minimal broken structure:

```
<navMap>
  <navPoint id="navPoint-1" playOrder="1">
    <navLabel><text/></navLabel>
  </navPoint>
</navMap>
```

In epub.js src/navigation.js, ncxItem does:

```
content = qs(item, "content");
src = content.getAttribute("src");
```

When content is null, that throws — same as the `getAttribute` on null in the console.

EPUB3 nav parsing already guards this (navItem returns early if there is no `<a>/<span>`). NCX parsing does not skip invalid points.

Suggested fix:

```
content = qs(item, "content");
if (!content) return; // or return a stub with href: "" and skip in parseNcx
src = content.getAttribute("src");
```

Optionally also guard navLabel (navLabel can be missing or empty without breaking open).
